(function(g){var window=this;var y3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.Is(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},z3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},gua=function(a,b){var c=new g.Hs;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},hua=function(){this.u=[];
this.o=[]},A3=function(a,b){switch(b.kind){case "asr":iua(b,a.u);
break;default:iua(b,a.o)}},iua=function(a,b){g.Xa(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},B3=function(){g.z.call(this);
this.u=new hua;this.B=[]},C3=function(a,b,c){B3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.Cw},D3=function(){this.segments=[]},jua=function(a,b){var c=g.pb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.cb(a.segments,c),g.cb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.kb(a.segments,c,0,b),g.kb(a.segments,c+1,0,b)))},E3=function(a,b,c,d,e,f){g.z.call(this);
this.policy=a;this.player=b;this.R=c;this.D=d;this.C=e;this.H=f;this.J=this.player.O();this.B=new D3;this.u=this.A=this.o=null;this.G=new g.H(this.Oy,1E3,this);this.events=new g.ur(this);g.A(this,this.G);g.A(this,this.events);this.events.M(b,"SEEK_COMPLETE",this.jB);this.jB();this.Oy()},kua=function(a,b){var c=g.ex(b,a.policy,{}).lc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Xq(c,d,3,100).then(function(e){a.ha();var f=!(a.C?e.response:e.responseText)||400<=e.status,k=g.Bx(e);k?(e=g.ex(a.A,a.policy,{}),f=a.A,g.ax(f.u,e,k),f.requestId=e.get("req_id"),kua(a,a.A)):(f||null==a.D||(k=a.A.o[0],a.C?a.D(e.response,1E3*(k.startTime+a.player.Db())):a.D(e.responseText,1E3*(k.startTime+a.player.Db()))),a.A=null,a.u=null)});
a.A=b;jua(a.B,a.A.o[0].u)},F3=function(a,b){B3.call(this,b.O());
this.ma=a;this.K=b;this.o=null;this.A=!1;this.C=g.cz(this.K.O())&&!this.ma.u},lua=function(a,b){var c=[],d;
for(d in a.ma.o)if(a.ma.o.hasOwnProperty(d)){var e=a.ma.o[d];if(g.EL(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Hs({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},mua=function(a,b){return null!=b&&b in a.ma.o?a.ma.o[b]:null},nua=function(a,b,c){var d=[],e;
for(e in a.ma.o)if(a.ma.o.hasOwnProperty(e)){var f=a.ma.o[e];if(g.EL(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},G3=function(a,b,c,d,e){B3.call(this,e||null);
this.videoId=b;this.py=d;this.C={};this.o=null;b=c||g.bq(a).hl||"";b=b.split("_").join("-");this.A=g.dq(a,{hl:b})},H3=function(a,b,c,d,e,f,k){var l={};
g.Ra(l,b);g.Ra(l,a.params);g.Ra(l,c);var m={};g.Ra(m,b.Bb);a.params.Bb&&g.Ra(m,a.params.Bb);g.Ra(m,c.Bb);l.Bb=m;g.Q.call(this,{F:"div",I:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},L:[{F:"span",I:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.D=[];this.U=!1;this.A=a;this.ba=this.V=null;this.playerWidth=e;this.playerHeight=f;this.experiments=k;this.G=null;this.maxWidth=.96*e;this.va=.96*f;this.u=l;
this.Da=c;this.C=this.o["captions-text"];this.ya=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.aa=d/360*16;this.type=0;this.fa=this.aa*oua(m);a=new g.Ar(this.element,!0);g.A(this,a);a.subscribe("dragstart",this.ZK,this);a.subscribe("dragmove",this.YK,this);a.subscribe("dragend",this.WK,this);this.ra=this.ka=0;b="";this.u.windowOpacity&&(a=g.w1(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":pua[this.u.textAlign]};this.ya&&(a["border-radius"]=b?this.fa/8+"px":"");if(this.B=2===this.A.params.o||3===this.A.params.o)b=this.element,c="vertical-rl",1===this.u.A&&(c="vertical-lr"),g.he&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.th(b,"-o-writing-mode",c),g.th(b,"-webkit-writing-mode",c),g.th(b,"writing-mode",c),g.th(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.A.params.o&&(g.th(b,"text-orientation",
""),g.th(b,"transform","rotate(180deg)"));g.th(this.element,a);switch(this.u.Ke){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},oua=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},qua=function(a,b){var c={},d=b.background?b.background:a.u.Bb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Bb.backgroundOpacity;d=g.w1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ya&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*oua(b)+"px";d=1;e=b.color||a.u.Bb.color;if(b.color||null!=b.textOpacity)e=g.w1(e),d=null==b.textOpacity?a.u.Bb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.tr&&(k=e=b.tr);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.hl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Bb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ye&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.aG&&(c.visibility="hidden");1===b.my&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.fz||g.gz,3===a.A.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.mf||2===b.mf||3===b.mf||4===b.mf||5===b.mf)if(g.fz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.mf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},rua=function(a){a.G=g.oe("SPAN");
g.th(a.G,{display:"block"});g.I(a.G,"caption-visual-line");a.C.appendChild(a.G)},sua=function(a,b){var c=g.oe("SPAN");
g.th(c,{display:"inline-block","white-space":"pre-wrap"});g.th(c,qua(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.th(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.th(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},tua=function(a,b,c){a.U=a.U||!!c;
var d={};g.Ra(d,a.u.Bb);g.Ra(d,c||b.o);g.Ra(d,a.Da.Bb);(c=!a.G)&&rua(a);for(var e=a.V&&a.ba&&g.Ob(d,a.ba)?a.V:sua(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(rua(a),e=sua(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.pe(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.fz||!g.xh(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.xh(n.children[2],"text-emphasis-position")&&(m=a.B?"padding-left":"padding-bottom"),
g.je?g.th(e,m,"1em"):g.th(e,m,"0.5em")))}a.ba=d;a.V=e;a.D.push(b)},I3=function(a,b,c,d,e,f,k){H3.call(this,a,b,c,d,e,f,k);
this.type=1},J3=function(a,b,c,d,e,f,k){H3.call(this,a,b,c,d,e,f,k);
this.type=2;this.H=[];this.N=this.J=this.ca=0;this.S=NaN;this.wa=0;this.Aa=null;this.ea=new g.H(this.QM,433,this);g.I(this.element,"ytp-caption-window-rollup");g.A(this,this.ea);g.th(this.element,"overflow","hidden")},uua=function(a,b){return(a.B?b.offsetHeight:b.offsetWidth)+1},vua=function(a){if(isNaN(a.S)){var b=a.u.ah;
if(b){var c=g.oe("SPAN");g.ye(c,"\u2013".repeat(b));g.th(c,qua(a,a.u.Bb));a.C.appendChild(c);a.S=c.offsetWidth;a.C.removeChild(c)}else a.S=0}return a.S},wua=function(a,b){if(!b)return"";
a.B&&1!==a.A.params.A&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},xua=function(a){a.H=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.A.params.u,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.J=d;a.N=Math.max(vua(a),a.wa,uua(a,a.C))},yua=function(a,b){xua(a);
var c=a.H.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.J-c;if(c!==a.ca){var d=0<c&&0===a.ca;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.ea.Va());g.th(a.C,"transform",wua(a,c));a.ca=c}xua(a)},K3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.$B.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=k},L3=function(a,b,c,d,e){g.$B.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},zua=function(a){var b="_"+M3++;
return new L3(0,0x8000000000000,0,b,a)},Bua=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.Vb){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[q.getAttribute("p")];l=Aua(l.textContent,n.textContent,q.textContent,f.textContent,k);return new K3(a,b,e,c,l,d,m)}switch(m.Vb){case 9:case 10:m.mf=1;break;case 11:m.mf=2;break;case 12:m.mf=3;break;case 13:m.mf=4;break;case 14:m.mf=5}return new K3(a,b,e,c,l.textContent||"",d,m)},Aua=function(a,b,c,d,e){var f=g.hl(),k=
f?g.oe("DIV"):g.oe("RUBY"),l=g.oe("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.oe("DIV"):g.oe("RP");a.textContent=b;k.appendChild(a);b=f?g.oe("DIV"):g.oe("RT");b.textContent=c;k.appendChild(b);c=e.Vb;if(10===c||11===c||12===c||13===c||14===c)if(g.th(b,"text-emphasis-style","filled circle"),g.th(b,"text-emphasis-color","currentcolor"),g.th(b,"webkit-text-emphasis","filled circle"),11===e.Vb||13===e.Vb)g.th(b,"webkit-text-emphasis-position","under left"),g.th(b,"text-emphasis-position","under left");c=!0;if(4===e.Vb||7===e.Vb||12===e.Vb||
14===e.Vb)g.th(k,"ruby-position","over"),g.th(k,"-webkit-ruby-position","before");else if(5===e.Vb||6===e.Vb||11===e.Vb||13===e.Vb)g.th(k,"ruby-position","under"),g.th(k,"-webkit-ruby-position","after"),c=!1;e=f?g.oe("DIV"):g.oe("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.th(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.th(f,"display","none"),f=f.nextElementSibling,g.th(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.th(k.lastElementChild,"display","none"),d?(g.th(k,"padding-top","0.6em"),g.th(f,"top","0")):(g.th(k,"padding-bottom","0.6em"),g.th(f,"bottom","0")));return k},N3=function(){g.z.apply(this,arguments)},O3=function(a){N3.call(this);
this.D=a;this.B={};this.J={};this.R={};this.C="_"+M3++;this.H={};this.u=this.o=null;this.G=!0},P3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},R3=function(a,b){var c=P3(a,b);
return void 0!==c?c:null},T3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return S3.test(c),c},Cua=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.R[d]:a.D);d=R3(b,"mh");null!=d&&(c.hk=d);d=R3(b,"ju");null!=d&&(c.textAlign=d);d=R3(b,"pd");null!=d&&(c.o=d);d=R3(b,"sd");null!=d&&(c.A=d);d=T3(b,"wfc");null!=d&&(c.windowColor=d);d=P3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},Dua=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.J[d]);d=R3(b,"ap");null!=d&&(c.Ke=d);d=P3(b,"cc");null!=d&&(c.ah=d);d=P3(b,"ah");null!=d&&(c.he=d);d=P3(b,"rc");null!=d&&(c.u=d);d=P3(b,"av");null!=d&&(c.qf=d);return c},Eua=function(a,b,c,d){var e={};
g.Ra(e,Dua(a,b));g.Ra(e,Cua(a,b));d?g.Ob(e,a.D)?(d=a.C,e=a.D):d="_"+M3++:d=b.getAttribute("id")||"_"+M3++;a=P3(b,"t")+c;b=P3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.ah,e.ah=c;return new L3(a,b,0,d,e)},U3=function(a){N3.call(this);
this.D=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},V3=function(a){a=g.Md(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Fua=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.ah=b);if(2===f.o||3===f.o)b=f.u,f.u=f.ah,f.ah=b;return new L3(c,d,0,e,f)},X3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new W3(this);this.C=new W3(this);this.o=[];this.clear()},Hua=function(a,b,c){if(255===a&&255===b||!a&&!b)return{ni:a,
Xg:b,result:0};a=Gua[a];b=Gua[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Xg===d;if(d)return{ni:a,Xg:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ni:a,Xg:b,result:2};return{ni:a,Xg:b,result:3}},Jua=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Iua(a.B,b,c,d))},Kua=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Jua(a,d.Ew,d.Fw,b):1===d.type&&a.u&496&&Iua(a.C,d.Ew,d.Fw,b);a.o.length=0},Y3=function(){this.type=0},Z3=function(){this.state=this.Xg=this.ni=0},Lua=function(){this.timestamp=this.o=0},$3=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new Y3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new Lua}},a4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!==t.o){0===c&&(c=m,d=q);n=String.fromCharCode(t.o);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===t.o||32===q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],t=q.o,0!==t&&(0===c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===t)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},Qua=function(a,b){switch(a){case 0:return Mua[(b&127)-32];
case 1:return Nua[b&15];case 2:return Oua[b&31];case 3:return Pua[b&31]}return 0},b4=function(a){return a.A[a.row][a.u]},c4=function(a,b,c){2<=b&&1<a.u&&(--a.u,b4(a).o=0);
var d=b4(a);d.timestamp=a.C.time+0;d.o=Qua(b,c);32>a.u&&a.u++},Rua=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.A[b+e][f],l=a.A[c+e][f];
k.o=l.o;k.timestamp=l.timestamp}},d4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},e4=function(a){a.row=0<a.o?a.o:1;
a.u=1;d4(a,0,15)},f4=function(a){this.A=a;
this.C=0;this.style=new Y3;this.D=new $3(this.A);this.G=new $3(this.A);this.text=new $3(this.A);this.u=this.D;this.B=this.G;this.o=this.u},g4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(a4(d,c),e4(a.u),e4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(a4(d,c),d4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},Sua=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},Tua=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},W3=function(a){this.u=a;
this.C=0;this.A=new f4(this.u);this.D=new f4(this.u);this.o=new Z3;this.B=this.A},Iua=function(a,b,c,d){a.o.update();
b=Hua(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ni;c=b.Xg;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&c4(a,0,b),c&96&&c4(a,0,c),0!==b&&0!==c&&3===a.style.type&&a4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.ni=e,b.Xg=c,b.state=2,b=e&8?a.D:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,k=1+d-c.o;Rua(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));d4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:c4(b.o,0,32);break a;case 48:57===c?(d=b.o,b4(d).o=0,32>d.u&&d.u++):c4(b.o,1,c&15)}break;case 2:c&32&&c4(b.o,2,c&31);break;case 3:c&32&&c4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Sua(b);
break;case 33:d=b.o;1<d.u&&(--d.u,b4(d).o=0);break;case 36:d=b.o;b=b4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:g4(b,2,d);break;case 38:g4(b,3,d);break;case 39:g4(b,4,d);break;case 40:c4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);e4(d);Tua(b);break;case 43:Tua(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:a4(a,d)}d4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;a4(a,d);Rua(a,b,b+1,a.o-1);d4(a,a.row,1)}break;case 46:d4(b.B,0,15);break;case 47:a4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,Sua(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},Uua=function(){},h4=function(a,b,c){this.H=a;
this.G=c;this.version=this.D=this.B=this.o=0;this.u=new DataView(this.H);this.A=[]},i4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},j4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},k4=function(a,b){N3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new X3;this.o.u=1<<this.track},l4=function(a){if("string"===typeof a)return!1;
a=new h4(a,8,0);return Vua(a)},Vua=function(a){if(!(a.o<a.u.byteLength)||1380139777!==j4(a))return!1;
a.version=i4(a);if(1<a.version)return!1;i4(a);i4(a);i4(a);return!0},m4=function(){N3.call(this)},Wua=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Ye=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3===q.nodeType)q=new K3(b,c,d,e.id,q.nodeValue,f||0<n,g.Mb(l)?void 0:l),m.push(q),e.o.push(q);else{var t={};g.Ra(t,l);Wua(a,b,c,d,e,!0,q,t,m)}}},n4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Xua=function(a,b,c,d){d=Object.assign({hk:0},d);
return new L3(a,b,c,"_"+M3++,d)},o4=function(a){g.z.call(this);
this.u=a;this.o=null},Zua=function(a){var b={};
if(a=z3(a))b.lang=a,Yua.test(a)&&(b.o=1);return b},r4=function(a){g.DL.call(this,a);
this.K=a;this.A=this.K.O();this.videoData=this.K.getVideoData();this.wa=g.YK(this.K);this.B={Bb:{}};this.D={Bb:{}};this.N=[];this.J={};this.ca={};this.U=!1;this.ra=g.FL(this.videoData,this.K);this.ya=!!this.videoData.captionTracks.length;this.Aa=!!this.videoData.ql;this.fa="3"===this.A.controlsType;this.u=this.G=this.H=this.aa=this.ka=null;this.ea=new o4(this.A);this.o=null;this.V=new g.ur(this);var b=null,c=g.lo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Vn(c));this.ga=b;b=a.app.C;
c=!(!b||!b.Um());this.va=!(!b||!b.pj());this.C=this.fa&&c&&!this.ra;this.R=!this.C&&this.fa&&this.va&&this.ra;g.A(this,this.ea);this.C?this.ba=this.S=null:(this.S=new g.sn(this.MC,void 0,this),g.A(this,this.S),this.ba=new g.H(this.eO,2E3,this),g.A(this,this.ba));g.A(this,this.V);this.C||this.V.M(a,"resize",this.jv);this.V.M(a,"onPlaybackAudioChange",this.uK);this.V.M(a,g.cC("captions"),this.KH,this);this.V.M(a,"crx_captions",this.LH,this);p4(this,q4(this,"display-settings")||{})},s4=function(a){if(1===
a.A.Zg||1===a.videoData.Zg||"alwayson"===g.uB(a.videoData,"yt:cc"))return!0;
if(2===a.A.Zg){var b=q4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().qr;return"ON"===c||"on"===g.uB(a.videoData,"yt:cc")},t4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.ao||"FORCED_ON"===c.qr},v4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.Aa?!1:a.ya?!1:!0);c=a.u.Ei(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.uB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(z3(c[f])===d[e])return c[f];return a.G&&a.G.Cr?a.G.Cr:(d=c.find(function(k){return k.isDefault}))?d:c[0]||u4(a)}return null},u4=function(a){return a.G&&a.G.ao},w4=function(a){var b=u4(a);
return!!b&&a.o===b},$ua=function(a,b){for(var c=a.K.app.C.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},y4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.U=c,a.U&&x4(a,"module-enabled",!!b));a.o=b;t4(a)&&(a.o=u4(a));a.load()},ava=function(a,b){var c=a.wa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&Yua.test(d)&&(b.params.o=1);d=a.wa.getPlayerSize();switch(null!=b.params.hk?b.params.hk:1<b.o.length?1:0){case 1:return new I3(b,a.B,a.D,c,d.width,d.height,a.A.experiments);case 2:return new J3(b,a.B,a.D,c,d.width,d.height,a.A.experiments);default:return new H3(b,a.B,a.D,c,d.width,d.height,a.A.experiments)}},p4=function(a,b,c){c=void 0===c?!1:c;
var d=z4.Bb;a.B={};g.Ra(a.B,z4);a.B.Bb={};g.Ra(a.B.Bb,d);a.D={Bb:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;S3.test(f);e.Bb.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;S3.test(f);e.Bb.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||z4.windowColor;S3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Bb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Bb.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Ye?3:d.bold?1:d.Ye?2:0);f=f.Bb;switch(e){case 1:f.bold=!0;delete f.Ye;break;case 2:delete f.bold;f.Ye=!0;break;case 3:f.bold=!0;f.Ye=!0;break;default:delete f.bold,delete f.Ye}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Bb.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=z4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Bb.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Bb.fontFamily=f;a.loaded&&a.jv();c&&x4(a,"display-settings",b)},cva=function(a,b){if(b&&!a.H){var c=zua({o:0,
lang:"en"});a.H=[c,new K3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.mL(a.player,a.H)}else!b&&a.H&&(bva(a,a.H),a.H=null)},bva=function(a,b){g.sT(a.player.app,b,void 0);
(0,g.x)(b,function(c){g.db(this.N,c)},a);
a.S.Va()},q4=function(a,b){if(!a.ga)return null;
try{var c=a.ga.get(b)}catch(d){a.ga.remove(b)}return c},x4=function(a,b,c){if(a.ga)try{a.ga.set(b,c)}catch(d){}};
g.UL.prototype.rl=g.ca(11,function(){for(var a=g.ae(document,"track",void 0,this.o),b=0;b<a.length;b++)g.te(a[b])});
g.YL.prototype.rl=g.ca(10,function(){this.o.rl()});
g.UL.prototype.Um=g.ca(9,function(){return!!this.o.textTracks});
g.YL.prototype.Um=g.ca(8,function(){return this.o.Um()});
g.UL.prototype.kl=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.YL.prototype.kl=g.ca(6,function(a){this.o.kl(a)});
g.mC.prototype.pj=g.ca(5,function(){});
g.UL.prototype.pj=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.YL.prototype.pj=g.ca(3,function(){return this.o.pj()});
g.Mu.prototype.qo=g.ca(1,function(a){return(a=this.rg(a))?a.o:0});
g.wx.prototype.qo=g.ca(0,function(){return 0});
var Yua=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;hua.prototype.Ei=function(a){return a?this.o.concat(this.u):this.o};
g.r(B3,g.z);g.h=B3.prototype;g.h.Ei=function(a){return this.u.Ei(a)};
g.h.Qo=function(){};
g.h.Ro=function(){};
g.h.Ng=function(){};
g.h.Nj=function(){return""};
g.h.DB=function(){return!1};
g.h.Y=function(){this.Ng();g.z.prototype.Y.call(this)};
g.r(C3,B3);C3.prototype.Qo=function(a,b,c){var d=this;this.ha();b=this.Nj(a,b);this.Ng();this.o=g.tq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
C3.prototype.Ro=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())A3(this.u,c.value);a()};
C3.prototype.Nj=function(a,b){var c=a.lc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.hl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=z3(a));return g.dq(c,d)};
C3.prototype.Ng=function(){this.o&&this.o.abort()};
D3.prototype.contains=function(a){a=g.pb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
D3.prototype.length=function(){return this.segments.length/2};
g.r(E3,g.z);g.h=E3.prototype;g.h.Y=function(){g.z.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.jB=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.Db();var b=this.o;this.o=g.Va(this.R.vg(a).o);b!==this.o&&this.H&&this.H()};
g.h.reset=function(){this.B=new D3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Oy=function(){this.ha();var a;if(a=null!=this.o)a=this.o,a=a.o.Gg(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.mh(),a.o[0].duration?(this.B.contains(a.o[0].u)||kua(this,a),this.o=g.Va(a.o)):!g.O(this.J.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.D&&this.o.D+this.player.Db()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.r(F3,B3);g.h=F3.prototype;g.h.Qo=function(a,b,c){var d=this;this.Ng();b=mua(this,a.getId());b||(b=a.languageCode,b=this.ma.u?nua(this,b,"386"):nua(this,b));if(b){var e=1E3*(b.index.qo(b.index.Ue())-b.index.md(b.index.Ue()));this.o=new E3(new g.xw,this.K,b,function(f,k){c(f,a,k,e)},this.C||g.Ws(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.h.DB=function(){var a=this.A;this.A=!1;return a};
g.h.Ro=function(a){var b;this.C?b=[new g.Hs({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Hs({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ma.u?lua(this,"386"):lua(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())A3(this.u,c.value);a()};
g.h.Ng=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.Nj=function(){return""};
g.r(G3,B3);G3.prototype.Qo=function(a,b,c){var d=this;this.ha();b=this.Nj(a,b);this.Ng();this.o=g.tq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
G3.prototype.Ro=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.py&&(d.asrs=1);c=g.dq(c,d);this.Ng();this.o=g.tq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),k=0;k<f.length;k++){var l=f[k],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),t=l.getAttribute("kind"),u=l.getAttribute("id"),y="true"===l.getAttribute("lang_default"),B="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");A3(b.u,new g.Hs({languageCode:m,languageName:n,name:q,kind:t,id:u,is_servable:!0,is_translateable:B,vss_id:l,is_default:y}))}e=e.getElementsByTagName("target");f=e.length;for(k=0;k<f;k++)m={languageCode:e[k].getAttribute("lang_code"),languageName:e[k].getAttribute("lang_translated"),languageOriginal:e[k].getAttribute("lang_original"),id:e[k].getAttribute("id"),isDefault:"true"===e[k].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
G3.prototype.Nj=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=z3(a));return c=g.dq(c,d)};
G3.prototype.Ng=function(){this.o&&this.o.abort()};
var S3=/^#(?:[0-9a-f]{3}){1,2}$/i;var pua=["left","right","center","justify"];g.r(H3,g.Q);g.h=H3.prototype;g.h.ZK=function(a,b){var c=g.Jh(this.element,this.element.parentElement);this.ka=a-c.x;this.ra=b-c.y;g.I(this.element,"ytp-dragging")};
g.h.YK=function(a,b){var c=g.Mh(this.element),d=a-this.ka-.02*this.playerWidth,e=b-this.ra-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Md(f,0,2));var k=(e+c.height/2)/this.va*3;k=Math.floor(g.Md(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Md(d,0,1);c=(e+k/2*c.height)/this.va;c=100*g.Md(c,0,1);this.A.params.Ke=l;this.A.params.qf=c;this.A.params.he=d;this.u.Ke=l;this.u.qf=c;this.u.he=d;this.dC()};
g.h.WK=function(){g.En(this.element,"ytp-dragging")};
g.h.dC=function(){this.nj(this.D)};
g.h.nj=function(a){var b=Math.min(this.Fx(),this.maxWidth),c=this.Ex(),d="";3===this.A.params.o&&(d="rotate(180deg)");g.th(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.gr(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.he+2;d=this.u.Ke;switch(d){case 0:case 3:case 6:b=this.u.Bb.fontSizeIncrement;!g.O(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.o&&3!==this.u.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.qf+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.th(this.element,a)};
g.h.gr=function(a){var b;for(b=0;b<a.length&&a[b]===this.D[b];b++);if(this.U||this.D.length>b)b=0,this.U=!1,this.D=[],this.G=this.ba=this.V=null,g.re(this.C);for(;b<a.length;b++)tua(this,a[b])};
g.h.Fx=function(){return 0};
g.h.Ex=function(){return 0};
g.h.toString=function(){return g.Q.prototype.toString.call(this)};g.r(I3,H3);I3.prototype.gr=function(a){var b=this.A.o;H3.prototype.gr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Ra(d,c.o);g.Ra(d,dva);var e=c.o;var f=d}tua(this,c,d)}};
var dva={aG:!0};g.r(J3,H3);g.h=J3.prototype;g.h.dC=function(){g.vn(this.ea)};
g.h.QM=function(){g.En(this.element,"ytp-rollup-mode");this.nj(this.Aa,!0)};
g.h.Ex=function(){return this.B?this.N:this.J};
g.h.Fx=function(){return this.B?this.J:this.N};
g.h.nj=function(a,b){this.Aa=a;if(this.A.params.u){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));this.wa=this.N;this.J=this.N=0;H3.prototype.nj.call(this,a);yua(this,b);H3.prototype.nj.call(this,a)}else H3.prototype.nj.call(this,a)};g.r(K3,g.$B);K3.prototype.toString=function(){return g.$B.prototype.toString.call(this)};g.r(L3,g.$B);L3.prototype.toString=function(){return g.$B.prototype.toString.call(this)};
var M3=0;g.r(N3,g.z);N3.prototype.A=function(){return[]};
N3.prototype.reset=function(){};g.r(O3,N3);O3.prototype.reset=function(){this.H={};this.u=this.o=null;this.G=!0};
O3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.B,l={},m=c.getAttribute("p");m&&g.Ra(l,this.B[m]);m=Q3(c,"b");null!=m&&
(l.bold=m);m=Q3(c,"i");null!=m&&(l.Ye=m);m=Q3(c,"u");null!=m&&(l.underline=m);m=R3(c,"et");null!=m&&(l.charEdgeStyle=m);m=R3(c,"of");null!=m&&(l.offset=m);m=T3(c,"bc");null!=m&&(l.background=m);m=T3(c,"ec");null!=m&&(l.tr=m);m=T3(c,"fc");null!=m&&(l.color=m);m=R3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=P3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=P3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=P3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=R3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Vb=
10<m?m-1:m);c=R3(c,"hg");null!=c&&(l.my=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.R[d]=Cua(this,c);break;case "wp":d=c.getAttribute("id"),this.J[d]=Dua(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=Eua(this,d,e,!1);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.C;m=!!Q3(d,
"a");n=(P3(d,"t")||0)+n;var q=P3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var y=Array.from(d.childNodes);y.length&&(this.G=null!=d.getAttribute("d"));for(var B=0;B<y.length;B++){var D=y[B],E=void 0;0<B&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=(D=F.getAttribute("p"))?this.B[D]:null)&&D.Vb&&(1===D.Vb?(D=y.slice(B,B+4),4===D.length&&
(E=Bua(n,q,l,m,t,D,this.B),B+=3)):E=Bua(n,q,l,m,t,[F],this.B)),!E){var G=F;E=n;F=q;D=l;var ha=m,na=t,cc=G.textContent?G.textContent:"",vc=G.getAttribute("p");vc=vc?this.B[vc]:null;G=P3(G,"t")||0;E=new K3(E+G,F-G,na,D,cc,ha,vc)}}else E=new K3(n,q,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId===this.C&&(this.o=Eua(this,d,e,!0),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var eva=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(U3,N3);U3.prototype.reset=function(){this.u.clear()};
U3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.Ye=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(k.tr=V3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);void 0!==
f.fcForeColor&&(k.color=V3(f.fcForeColor));void 0!==f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(k.background=V3(f.bcBackColor));void 0!==f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.Vb=10<l?l-1:l,k.mf=eva.get(k.Vb));f.hgHorizGroup&&(k.my=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.C.get(l)):Object.assign(k,this.D),void 0!==
f.mhModeHint&&(k.hk=f.mhModeHint),void 0!==f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(k.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(k.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(k.windowColor=V3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.B.get(l)),void 0!==f.ahHorPos&&(k.he=f.ahHorPos),
void 0!==f.apPoint&&(k.Ke=f.apPoint),void 0!==f.avVerPos&&(k.qf=f.avVerPos),void 0!==f.ccCols&&(k.ah=f.ccCols),void 0!==f.rcRows&&(k.u=f.rcRows),this.B.set(d++,k);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=Fua(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+M3++,l=Fua(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=!!m.aAppend,q=n?
6:5,t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var y=t[m],B=y.utf8;if(B){var D=y.tOffsetMs||0,E=null;y.pPenId&&(E=this.o.get(y.pPenId));if(2===(null!=l.params.hk?l.params.hk:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(y=E&&1===E.Vb)if(y=m,y+3>=t.length||!t[y+1].pPenId||!t[y+2].pPenId||!t[y+3].pPenId)y=!1;else{var F=t[y+1].pPenId;(F=this.o.get(F))&&F.Vb&&2===F.Vb?(F=t[y+2].pPenId,F=this.o.get(F),!F||!F.Vb||3>F.Vb?y=!1:(F=t[y+3].pPenId,y=(F=this.o.get(F))&&F.Vb&&2===F.Vb?
!0:!1)):y=!1}if(y){D=t[m+1].utf8;y=t[m+3].utf8;F=t[m+2].utf8;var G=this.o.get(t[m+2].pPenId);B=Aua(B,D,F,y,G);n=new K3(e,f,q,k,B,n,E);m+=3}else n=new K3(e+D,f-D,q,l.id,B,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};X3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
X3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Gua=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Y3.prototype.set=function(a){this.type=a};
Y3.prototype.get=function(){return this.type};
Z3.prototype.clear=function(){this.state=0};
Z3.prototype.update=function(){this.state=2===this.state?1:0};
Z3.prototype.isValid=function(){return 0!==this.state};
Z3.prototype.matches=function(a,b){return this.isValid()&&a===this.ni&&b===this.Xg};
Lua.prototype.reset=function(){this.timestamp=this.o=0};
$3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
$3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
$3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var Mua=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Nua=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Oua=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Pua=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];f4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.D;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.D.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
W3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};Uua.prototype.C=function(){};g.r(h4,Uua);h4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+M3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new L3(c,d-c,5,f,{textAlign:0,Ke:0,he:2.5*b,qf:5.33*a});e=new K3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.r(k4,N3);k4.prototype.A=function(a){a=new h4(a,a.byteLength,this.u);if(Vua(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=j4(a)*(1E3/45):1===a.version&&(a.B=4294967296*j4(a)+j4(a)),a.D=i4(a);0<a.D;a.D--){var b=i4(a),c=i4(a),d=i4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,Ew:c,Fw:d,order:b.o.length}))}Kua(this.o,a);return a.A}return[]};
k4.prototype.reset=function(){this.o.clear()};g.r(m4,N3);
m4.prototype.A=function(a,b){for(var c=[],d=a.split(fva),e=1;e<d.length;e++){var f=d[e],k=b;if(""!==f&&!gva.test(f)){var l=A4.exec(f);if(l&&4<=l.length){var m=n4(l[1]),n=n4(l[2])-m;m+=k;var q=(l=l[3])?l.split(" "):[];l={};var t=null,u="",y=null,B="";l.textAlign=2;q=g.p(q);for(var D=q.next();!D.done;D=q.next())if(D=D.value.split(":"),2===D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(t=D[0],l.qf=Number.parseInt(t,10),2===D.length&&(u=D[1].trim()));break;case "position":D=
E.split(",");y=D[0];l.he=Number.parseInt(y,10);2===D.length&&(B=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}t||(l.qf=100,u||(u="end"));if(!y)switch(l.textAlign){case 0:l.he=0;break;case 1:l.he=100;break;default:l.he=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(B){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.Ke=0>t||8<t?7:t;f=f.substring(A4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");B=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))k=Xua(m,n,5,B),n=new K3(m,n,5,k.id,l,!1,g.Mb(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=l.split(hva),1===u.length?(l=5,B=Xua(m,n,l,B)):(t=l=6,B=Object.assign({ah:32},B),B=new L3(m,n,t,"_"+M3++,B)),c.push(B),t=m,y=0;y<u.length;y++)q=u[y],0===y%2?(D=g.x1("<html>"+q+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(q))):E=D.firstChild,Wua(this,t,n-(t-m),l,B,0<y,E,f,c)):t=n4(q)+k}A4.lastIndex=0}}return c};
var gva=/^NOTE/,fva=/(?:\r\n|\r|\n){2,}/,A4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),hva=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(o4,g.z);o4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
o4.prototype.reset=function(){this.o&&this.o.reset()};
o4.prototype.Y=function(){g.z.prototype.Y.call(this);this.clear()};var z4={windowColor:"#080808",windowOpacity:0,textAlign:2,Ke:7,he:50,qf:100,Bb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(r4,g.DL);g.h=r4.prototype;g.h.Y=function(){if(this.C||this.R){var a=this.K.app.C;a&&!a.ha()&&a.rl()}else cva(this,!1);g.DL.prototype.Y.call(this)};
g.h.load=function(){var a=this;g.DL.prototype.load.call(this);var b=!g.O(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.ea.clear(),this.C?$ua(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Qo(this.o,"json3",function(d,e,f,k){if(d){a.u.DB()&&(a.N=[],g.uR(a.K.app,"captions",void 0),a.S.Va(),a.ea.reset());var l=a.ea;f=f||0;k=k||0;if(l.u.ia("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.bv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),l4(d)||(d=g.Zf(new Uint8Array(d))))}}else"string"===typeof d||l4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.bv(m,0,1835295092))&&m.size?g.Zf(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,t=k;if(!l4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new k4(t,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,t=f,l.o||(l.o=new m4),q=l.o.A(e,t),.01>Math.random()&&g.Iq(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new U3(Zua(e)));n=l.o.A(q,f);break b}catch(G){g.Hq(G);n=[];break b}t=g.x1(q);if(!t||!t.firstChild){var y=Error("Invalid caption track data");y.params=q;throw y;}if("timedtext"===t.firstChild.tagName){if(3===Number(t.firstChild.getAttribute("format"))){l.o||(l.o=new O3(Zua(e),l.u));n=l.o.A(t,f);break b}var B=Error("Unsupported subtitles format in web player (Format2)");
B.params=q;throw B;}if("transcript"===t.firstChild.tagName){var D=Error("Unsupported subtitles format in web player (Format1)");D.params=q;throw D;}var E=Error("Invalid caption track data");E.params=q;throw E;}u=n}var F=u}catch(G){g.Hq(G),l.clear(),F=[]}else F=[];g.mL(a.player,F);!a.U||a.R||w4(a)||g.Ry(a.A)||g.Sy(a.A)||(a.ba.Te(),F=zua({Ke:0,he:5,qf:5,u:2,textAlign:0,o:0,lang:"en"}),a.aa=[F],l=["Click "," for settings"],a.ka||(u=new g.Bu(g.dN()),g.A(a,u),a.ka=u.element),u=F.end-F.start,(e=g.Is(a.o))&&
a.aa.push(new K3(F.start,u,0,F.id,e)),a.aa.push(new K3(F.start,u,0,F.id,l[0]),new K3(F.start,u,0,F.id,a.ka,!0),new K3(F.start,u,0,F.id,l[1],!0)),g.mL(a.player,a.aa),a.ba.Va());!a.U||a.R||w4(a)||(x4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.V(a.player.app))&&g.rI(F.C));a.U=!1}}),!b||this.C||this.R||w4(this)||this.player.sa("captionschanged",y3(this.o))),b||(this.o&&!w4(this)?this.player.sa("captionschanged",y3(this.o)):this.player.sa("onCaptionsTrackListChanged"));
else{var c;this.ra?c=new F3(this.videoData.ma,this.player):this.ya?c=new C3(this.A,this.videoData,this.player.getAudioTrack()):c=new G3(this.videoData.ql,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.uB(this.videoData,"yt:cc_default_lang")||this.A.Mc,this.videoData.mr,this.A);this.u=c;g.A(this,this.u);c.Ro(function(){var d;a.U||s4(a)?d=v4(a,a.U):t4(a)&&(d=u4(a));if(a.C||a.R){for(var e=a.u.Ei(!0),f=[],k=0;k<e.length;k++){var l=e[k],m=g.ne("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.Is(l));m.setAttribute("srclang",z3(l));m.setAttribute("id",l.toString());a.R||m.setAttribute("src",a.u.Nj(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.K.app.C;d.kl(f);f=d.xa();a.va&&a.V.M(f.textTracks,"change",a.sN)}else!a.o&&d&&y4(a,d),a.player.sa("onCaptionsTrackListChanged"),a.player.sa("onApiChange")})}};
g.h.unload=function(){this.C&&this.o?$ua(this,!1):(this.ba&&this.ba.Te(),g.uR(this.player.app,"captions",void 0),this.N=[],this.u&&this.u.Ng(),this.ea.clear(),this.H&&g.mL(this.player,this.H),this.jv());g.DL.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.rI(a.C);this.player.sa("captionschanged",{})};
g.h.create=function(){(this.fa?this.C||this.R:t4(this)||s4(this))&&this.load()};
g.h.getTrackById=function(a){for(var b=this.u.Ei(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.h.sN=function(){for(var a=this.K.app.C.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&y4(this,b,!0)};
g.h.SO=function(){!this.o&&this.C||this.unload()};
g.h.KH=function(a){this.N.push(a);this.S.Va()};
g.h.LH=function(a){g.db(this.N,a);this.u instanceof F3&&this.u.C&&g.sT(this.player.app,[a],void 0);this.S.Va()};
g.h.YN=function(a){if(a instanceof L3){var b=this.J[a.id];b&&b.A!==a&&(b.dispose(),delete this.J[a.id],b=null);b||(b=ava(this,a))&&(this.J[a.id]=b)}else b=a.windowId,this.ca[b]||(this.ca[b]=[]),this.ca[b].push(a)};
g.h.eO=function(){bva(this,this.aa);this.aa=null};
g.h.MC=function(){var a=this;this.S.stop();g.Nb(this.ca);this.N.sort(g.bC);var b=this.N;if(this.H){var c=(0,g.ue)(b,function(d){return-1===this.H.indexOf(d)},this);
c.length&&(b=c)}(0,g.x)(b,this.YN,this);g.zb(this.J,function(d,e){a.ca[e]?(d.element.parentNode||(d instanceof J3||d instanceof I3||g.Cb(a.J,function(f,k){k!==e&&f.A.params.Ke===d.A.params.Ke&&f.A.params.he===d.A.params.he&&f.A.params.qf===d.A.params.qf&&(f.dispose(),delete a.J[k]);return k===e},a),g.qL(a.player,d.element,4)),d.nj(a.ca[e])):(d.dispose(),delete a.J[e])},this)};
g.h.lO=function(){p4(this,{},!0);g.O(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.sa("captionssettingschanged")};
g.h.pF=function(){var a=z4.Bb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ye?3:a.bold?1:a.Ye?2:0,textOpacity:a.textOpacity,windowColor:z4.windowColor,windowOpacity:z4.windowOpacity};var b=q4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.UC=function(a,b){var c={};g.Ra(c,q4(this,"display-settings"));g.Ra(c,a);p4(this,c,b);this.player.sa("captionssettingschanged")};
g.h.jv=function(){!this.C&&this.loaded&&(g.zb(this.J,function(a,b){a.dispose();delete this.J[b]},this),this.MC())};
g.h.Rc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Md(b,-2,4);this.UC({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&y4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&x4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Na(b))break;if(g.Mb(b)){y4(this,null,!0);break}for(var d=this.u.Ei(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
gua(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||y4(this,c,!0)}else return this.loaded&&this.o&&!w4(this)?y3(this.o):{};return"";case "tracklist":return this.u?(0,g.Dc)(this.u.Ei(!(!b||!b.includeAsr)),function(k){return y3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.C||void 0===b||cva(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.h.HG=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.h.MO=function(){this.loaded&&this.o&&!w4(this)?(x4(this,"module-enabled",!1),this.unload(),t4(this,!0)&&y4(this,u4(this),!1)):y4(this,w4(this)||!this.o?v4(this,!0):this.o,!0)};
g.h.uK=function(){var a=w4(this);t4(this,a)?y4(this,this.player.getAudioTrack().ao,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.C||this.R:t4(this)||s4(this))&&(a?y4(this,v4(this),!1):this.load()))};g.SL.captions=r4;})(_yt_player);
